import { EngineConfigurationOption, Text } from '@sonolus/core'

export const optionsDefinition = {
    strictJudgment: {
        name: Text.JudgmentStrict,
        category: 'gameplay',
        scope: 'Bandori',
        standard: true,
        advanced: true,
        type: 'toggle',
        def: 0,
    },
    speed: {
        name: Text.Speed,
        category: 'gameplay',
        standard: true,
        advanced: true,
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    hidden: {
        name: Text.Hidden,
        category: 'gameplay',
        standard: true,
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    noteSpeed: {
        name: Text.NoteSpeed,
        category: 'gameplay',
        scope: 'Bandori',
        type: 'slider',
        def: 5,
        min: 1,
        max: 15.9,
        step: 0.1,
    },
    mirror: {
        name: Text.Mirror,
        category: 'gameplay',
        type: 'toggle',
        def: 0,
    },
    sfxEnabled: {
        name: Text.Effect,
        category: 'audio',
        scope: 'Bandori',
        type: 'toggle',
        def: 1,
    },
    autoSFX: {
        name: Text.EffectAuto,
        category: 'audio',
        scope: 'Bandori',
        type: 'toggle',
        def: 0,
    },
    noteSize: {
        name: Text.NoteSize,
        category: 'graphics',
        scope: 'Bandori',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    noteEffectEnabled: {
        name: Text.NoteEffect,
        category: 'graphics',
        scope: 'Bandori',
        type: 'toggle',
        def: 1,
    },
    noteEffectSize: {
        name: Text.NoteEffectSize,
        category: 'graphics',
        scope: 'Bandori',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    markerAnimation: {
        name: Text.MarkerAnimation,
        category: 'graphics',
        scope: 'Bandori',
        type: 'toggle',
        def: 1,
    },
    simLineEnabled: {
        name: Text.Simline,
        category: 'graphics',
        scope: 'Bandori',
        type: 'toggle',
        def: 1,
    },
    connectorAlpha: {
        name: Text.ConnectorAlpha,
        category: 'graphics',
        scope: 'Bandori',
        type: 'slider',
        def: 0.8,
        min: 0.1,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    laneEffectEnabled: {
        name: Text.LaneEffect,
        category: 'graphics',
        scope: 'Bandori',
        type: 'toggle',
        def: 1,
    },
    slotEffectEnabled: {
        name: Text.SlotEffect,
        category: 'graphics',
        scope: 'Bandori',
        type: 'toggle',
        def: 1,
    },
    slotEffectSize: {
        name: Text.SlotEffectSize,
        category: 'graphics',
        scope: 'Bandori',
        type: 'slider',
        def: 1,
        min: 0,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    stageCover: {
        name: Text.StageCoverVertical,
        category: 'graphics',
        scope: 'Bandori',
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    lockStageAspectRatio: {
        name: Text.StageAspectratioLock,
        category: 'graphics',
        scope: 'Bandori',
        type: 'toggle',
        def: 1,
    },
    previewVerticalScale: {
        name: Text.PreviewScaleVertical,
        category: 'miscellaneous',
        scope: 'Bandori',
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    previewMeasure: {
        name: Text.PreviewMeasure,
        category: 'miscellaneous',
        scope: 'Bandori',
        type: 'toggle',
        def: 1,
    },
    previewBeat: {
        name: Text.PreviewBeat,
        category: 'miscellaneous',
        scope: 'Bandori',
        type: 'toggle',
        def: 1,
    },
    previewTime: {
        name: Text.PreviewTime,
        category: 'miscellaneous',
        scope: 'Bandori',
        type: 'toggle',
        def: 1,
    },
    previewBpm: {
        name: Text.PreviewBpm,
        category: 'miscellaneous',
        scope: 'Bandori',
        type: 'toggle',
        def: 1,
    },
} satisfies Record<string, EngineConfigurationOption>
